# Generated by Django 3.1.1 on 2020-11-12 07:36

from django.db import migrations


def populate_db(apps, schema_editor):

    Unit = apps.get_model('unitconv', 'Unit')

    #add the different units we need.
    kilogram = Unit(name="kg", valueInKiloGrams=1)
    kilogram.save()

    ImperialTon = Unit(name="T", valueInKiloGrams=1016.05)
    ImperialTon.save()

    gram = Unit(name="g", valueInKiloGrams=.001)
    gram.save()

    TroyOunce = Unit(name="t_oz", valueInKiloGrams=0.0311035)
    TroyOunce.save()

    Pound = Unit(name="lb", valueInKiloGrams=0.453592)
    Pound.save()

    Ounce = Unit(name="oz", valueInKiloGrams=0.0283495)
    Ounce.save()


class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
